### ISSUE TITLE
Need publish access

### ISSUE THREAD

**Issue by ellell** [micnews/rpc-http#23]
@kesla Can you add me as a collaborator at https://npmjs.com/rpc-http ?

**Comment by kesla** [comment]
done

**Comment by kesla** [comment]
can't close this one so you'll need to do that

**Comment by will123195** [comment]
Hej! Hope all is well. Miss you both!

**Comment by ellell** [comment]
@kesla thanks!

@will123195 hey! 👋miss you too!

**Comment by kesla** [comment]
@will123195 Hey will!
