### ISSUE TITLE
callback fires twice if there's an error in the callback

### ISSUE THREAD

**Issue by daedelus-j** [micnews/rpc-http#7]
https://github.com/micnews/rpc-http/blob/master/client.js#L33-L41

not sure if this is desired?

**Comment by ralphtheninja** [comment]
@daedelus-j That is not desired :)

**Comment by kesla** [comment]
how can the callback fire twice?

**Comment by kesla** [comment]
oh, if there's an error _in_ the callback. Now I see it :)

**Comment by daedelus-j** [comment]
https://github.com/micnews/rpc-http/pull/8
